global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  websecure:
    address: :443
    http:
      tls: {}

providers:
  docker:
    swarmMode: false
    network: traefik
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
  file:
    directory: /etc/traefik
    watch: true

api:
  insecure: true
  dashboard: true
  debug: true

log:
  filePath: /var/log/traefik.log
  level: DEBUG
  #format: json
accessLog:
  filePath: /var/log/access.log
  bufferingSize: 100
  #format: json
  #filters:
  #  statusCodes:
  #    - 400-499

